#测试端配置
server:
  port: 80
  servlet:
    context-path: /pybl
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-ia6vd64i.cd.tencentcdb.com:10028/visitor?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: flzxsqc!11
    #redis 连接
  redis:
    database: 0
    password: cwf #密码
    port: 6379
    addr: 106.52.245.57
    timeout: 10000
    jedis:
      pool:
        max-active: 8 #最大连接数
        max-idle: 200 #最大空闲连接数
        max-wait: 10000 #最大等待时间
        min-idle: 0

templateId: I-nNgggadJrZcZmkJzgxMVOptw4tf2MD9NKgYhWnCdM
#property配置
# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
#朋客联盟
#server.port=8098
#server.servlet.context-path=/weixin

#测试
#server.port=80
#server.servlet.context-path=/pybl
#坤坤测试环境
#spring.datasource.url=jdbc:mysql://134.175.44.10:3306/vistor?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
#spring.datasource.username=test
#spring.datasource.password=pd123456
#我的测试环境1
#spring.datasource.url=jdbc:mysql://47.106.82.190:3306/visitor?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
#spring.datasource.username=root
#spring.datasource.password=root
#我的测试环境2本地
#spring.datasource.url=jdbc:mysql://cdb-ia6vd64i.cd.tencentcdb.com:10028/visitor?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
#spring.datasource.username=root
#spring.datasource.password=flzxsqc!11
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#templateId=I-nNgggadJrZcZmkJzgxMVOptw4tf2MD9NKgYhWnCdM


