#测试端配置
server:
  port: 80
  servlet:
    context-path: /pybl
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/visitor?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
  redis:
    password: cwf #密码
    port: 6379
    addr: 106.52.245.57
    timeout: 10000
    jedis:
      pool:
        max-active: 8 #最大连接数
        max-idle: 200 #最大空闲连接数
        max-wait: 10000 #最大等待时间
        min-idle: 0

templateId: I-nNgggadJrZcZmkJzgxMVOptw4tf2MD9NKgYhWnCdM
