spring:
  profiles:
    #生产环境改为prod
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: true
    # 404 交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false
  thymeleaf:
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    #thymeleaf start
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/

component:
  appId: wx4aecbb914c5bcf48
  appSecret: 51942c5a17fa44ba11cae98e31a8cc74
debug: true
logging:
  level:
    com:
      company:
        project:
          dao: DEBUG


